# Generated by Django 5.2.2 on 2025-07-27 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('media_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueitem',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogue_photos', to='media_file.mediafile'),
        ),
    ]
