# Generated by Django 5.2.2 on 2025-07-27 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('downpayment', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid as downpayment', max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('due_date', models.DateField(help_text='When the order is meant to be delivered')),
                ('notes', models.TextField(blank=True)),
                ('is_fully_paid', models.BooleanField(default=False, help_text='Has the full payment been completed?')),
                ('date_downpayment_paid', models.DateField(blank=True, help_text='Date the downpayment was actually paid', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer')),
            ],
        ),
    ]
